# Generated by Django 3.0.5 on 2020-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200521_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=50, verbose_name='номер телефона'),
        ),
    ]
